server:
  port: 9443
  ssl:
    enabled: true
    key-alias: mtls-client
    key-store: classpath:mtls-client.p12
    key-password: password
    key-store-password: password
    key-store-type: PKCS12
    trust-store: classpath:mtls-truststore.p12
    trust-store-password: password
    trust-store-type: PKCS12
# If  client-auth is not set to "need", the server willnot request a client certificate and the client will not send one.
    client-auth: need
key-store: mtls-client.p12
key-password: password
key-store-password: password
key-store-type: PKCS12
spring:
  application:
    name: resource-server-mtls
  profiles:
    active: default
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8443
          jwk-set-uri: https://localhost:8443/oauth2/jwks

logging:
  config: classpath:logback.xml
  level:
    northwind: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
