server:
  port: 8443
  ssl:
    enabled: true
    key-alias: mtls-server
    key-store: classpath:mtls-server.p12
    key-store-password: password
    key-store-type: PKCS12
    key-password: password
    trust-store: classpath:mtls-truststore.p12
    trust-store-password: password
    trust-store-type: PKCS12
    # If  client-auth is not set to "need", the server willnot request a client certificate and the client will not send one.
    client-auth: need
security:
  require-ssl: true
spring:
  application:
    name: auth-server-mtls
  profiles:
    active: default

logging:
  config: classpath:logback.xml
  level:
    northwind: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

trust-store-file: mtls-truststore.p12
key-store-file: mtls-server.p12